all: timecli timecli6 timesrv

timecli: timecli.cpp
	g++ -Wall timecli.cpp ../../common.cpp -o timecli

timecli6: timecli6.cpp
	g++ -Wall timecli6.cpp ../../common.cpp -o timecli6

timesrv: timesrv.cpp
	g++ -Wall timesrv.cpp ../../common.cpp -o timesrv
